title: Stackbit Podcaster Theme
baseurl: /
permalink: '/:title/'
layout_type: boxed
style: bold
palette: red
mode: dark
base_font: sans-serif
header:
  type: header
  template: header
  title: Podcaster
  logo: images/logo.svg
  logo_alt: Podcaster logo
  has_primary_nav: true
  primary_nav_links:
    - type: action
      template: action
      label: Episodes
      url: /episodes
      style: link
    - type: action
      template: action
      label: About
      url: /about
      style: link
    - type: action
      template: action
      label: Sponsoring
      url: /advertising
      style: link
  has_secondary_nav: true
  secondary_nav_links:
    - type: action
      template: action
      label: Subscribe
      url: /subscribe
      style: primary
  has_anncmnt: true
  anncmnt_content: >-
    Curabitur ac tellus mattis, tempor ipsum eu, eleifend sapien. **[Learn
    More](/pricing/)**
  anncmnt_align: left
  anncmnt_is_home_only: true
  anncmnt_has_close: true
  anncmnt_id: new-episode
footer:
  type: footer
  template: footer
  logo: images/logo.svg
  logo_alt: Podcaster logo
  has_primary_nav: true
  primary_nav_links:
    - type: action
      template: action
      label: Episodes
      url: /episodes
      style: link
    - type: action
      template: action
      label: Subscribe
      url: /subscribe
      style: link
    - type: action
      template: action
      label: Advertising
      url: /advertising
      style: link
  has_secondary_nav: true
  secondary_nav_links:
    - type: action
      template: action
      label: About
      url: /about
      style: link
    - type: action
      template: action
      label: Terms
      url: /terms-conditions
      style: link
    - type: action
      template: action
      label: Privacy Policy
      url: /privacy-policy
      style: link
  has_tertiary_nav: false
  has_social: true
  social_links:
    - type: action
      template: action
      label: Twitter
      url: 'https://twitter.com/'
      style: link
      has_icon: true
      icon: twitter
      icon_position: center
      new_window: true
    - type: action
      template: action
      label: Facebook
      url: 'https://www.facebook.com/'
      style: link
      has_icon: true
      icon: facebook
      icon_position: center
      new_window: true
    - type: action
      template: action
      label: Instagram
      url: 'https://www.instagram.com/'
      style: link
      has_icon: true
      icon: instagram
      icon_position: center
      new_window: true
  content: >-
    &copy; Stackbit. All rights reserved. This Jamstack site was created with <a
    href="https://www.stackbit.com/?utm_source=deployed-footer" target="_blank"
    rel="noopener">Stackbit</a>. Create yours <a
    href="https://app.stackbit.com/create?theme=podcaster&utm_source=deployed-footer"
    target="_blank" rel="noopener">now</a>
sass:
  indentWidth: 4
  style: expanded
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
collections:
  posts:
    permalink: '/posts/:title/'
domain: 'https://superb-turtle-21803.netlify.app'
